import {
  pgTable,
  pgEnum,
  text,
  uuid,
  timestamp,
  boolean,
  integer,
  bigint,
  jsonb,
  date,
  primaryKey,
  index,
  uniqueIndex,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type {
  Questionnaire,
  QuestionnaireResponses,
  AudienceSpec,
  OrgPermissions,
  ProjectPermissions,
  CampHistoryEntry,
  SupplierOnboardingSteps,
} from "@quagga/types";

// Quagga Portal schema (AfrikaBurn Contributors App). The R0 core (migrations
// 0000–0008) is frozen per docs/build-spec.md §Schema; later features extend it
// ONLY by adding tables/columns behind a new append-only migration, never by
// altering or regenerating an earlier one (0009 notifications+bulletins,
// 0010 camp categories, 0011 supplier documents + account security).
// Feature/page agents do not touch this file at all.
//
// This file is the single hand-authored source of truth; everything under
// packages/db/migrations/ is GENERATED by drizzle-kit and never hand-edited.
// Change this file, run `pnpm --filter @quagga/db db:generate`, and commit both
// the SQL and its `meta/NNNN_snapshot.json` — the snapshot is not optional, it
// is what the NEXT generate diffs against. Hand-writing a migration skips it and
// breaks the generator for everyone after you (see AGENTS.md rule 1; the chain
// was broken this way between 0024 and 0028 and had to be repaired).
//
// Authentication/identity is SELF-HOSTED Better Auth (docs/auth-platform-spec.md).
// The Better Auth core tables (`user`, `session`, `account`, `verification`) and
// the DB rate-limit table (`rate_limit`) live in THIS database, owned by
// `@quagga/db` and mounted per app by `@quagga/auth`'s `drizzleAdapter`. They sit
// BESIDE our existing `users` table — the two are NOT merged — and our `users`
// row joins to the auth identity by `users.auth_user_id` → `user.id` as it always
// has (see the "Better Auth identity" section for the full rationale). Migration
// 0013 added the auth tables append-only; migrations 0000–0012 are untouched.

// --- Enums ---------------------------------------------------------------
// Each tuple mirrors a Zod enum in @quagga/types (the validation authority);
// this is the storage authority. Keep the two in sync.

export const groupKindEnum = pgEnum("group_kind", [
  "org",
  "theme_camp",
  "artwork",
  "mutant_vehicle",
]);

export const joinabilityEnum = pgEnum("joinability", ["open", "invite_only"]);

// Reserved: visibility is currently DERIVED (registered ⇒ public). This column
// exists so explicit privacy settings can land later without a migration.
export const groupVisibilityEnum = pgEnum("group_visibility", [
  "default",
  "public",
  "members_only",
  "private",
]);

// APPEND-ONLY, like every Postgres enum: `ALTER TYPE … ADD VALUE` can only add,
// never reorder or remove, so new ranks go at the END regardless of seniority.
// `god` is the rank the console PRESENTS as "System manager" — the stored value
// stays `god` deliberately (see @quagga/types roles.ts for why; don't rename it).
export const membershipRoleEnum = pgEnum("membership_role", [
  "god",
  "org_staff",
  "lead",
  "admin",
  "member",
  "engineer",
]);

export const inviteKindEnum = pgEnum("invite_kind", [
  "member",
  "lead_transfer",
]);

// Roles v2 (questionnaire-spec §"Role kinds"). `kind` governs permanence +
// assignment semantics; `color` is a curated palette key (token-mapped, not hex).
export const projectRoleKindEnum = pgEnum("project_role_kind", [
  "captain",
  "baseline",
  "default",
  "custom",
  "officer",
]);

// Org roles v1 (migration 0018). `system` rows are seeded and undeletable with
// EDITABLE rights; `custom` rows a System manager creates and deletes freely.
// The same permanence idea as `project_role_kind` above — one mental model.
export const orgRoleKindEnum = pgEnum("org_role_kind", ["system", "custom"]);
/** Migration 0022. `system` departments are seeded and undeletable; see
 * @quagga/types `OrgDepartmentKind` for why the load-bearing ones must exist. */
export const orgDepartmentKindEnum = pgEnum("org_department_kind", [
  "system",
  "custom",
]);

export const roleColorEnum = pgEnum("role_color", [
  "teal",
  "teal_deep",
  "apricot",
  "peach",
  "sage",
  "olive",
  "rust",
  "neutral",
]);

// Officer assignment consent (questionnaire-spec §"Officers are ALSO
// registrations"). Non-officer assignments are always `accepted`.
export const roleAssignmentConsentEnum = pgEnum("role_assignment_consent", [
  "pending",
  "accepted",
  "declined",
]);

export const registrationStatusEnum = pgEnum("registration_status", [
  "draft",
  "submitted",
  "under_review",
  "changes_requested",
  "approved",
  "rejected",
  "withdrawn",
]);

export const sectionKeyEnum = pgEnum("section_key", [
  "identity",
  "lnt",
  "participation",
  "size_logistics",
  "sound_placement",
  "suppliers_commerce",
]);

export const sectionReviewStatusEnum = pgEnum("section_review_status", [
  "open",
  "resolved",
]);

// Supplier model v2 (docs/supplier-spec.md). `vetting_status` + `source` are
// dead; `standing` is the org's single verdict, `supplier_note_kind` types the
// org-internal timeline. Step states are stored as jsonb (not an enum column)
// on `supplier_onboarding`.
export const supplierStandingEnum = pgEnum("supplier_standing", [
  "good",
  "watch",
  "suspended",
  "diligent_first_timer",
  "adapting",
  "absolute_beginner",
]);

// Whether an imported supplier is returning or a newbie (sheet "Returning
// Supplier?" column). Nullable on the row — blank sheet cells carry none.
export const supplierReturningEnum = pgEnum("supplier_returning", [
  "newbie",
  "returning",
]);

export const supplierNoteKindEnum = pgEnum("supplier_note_kind", [
  "infraction",
  "blessing",
  "note",
]);

// Org-controlled supplier documents (docs/accounts-security-spec.md §"Supplier
// documents"). `link` = external URL, `file` = uploaded asset; `url` carries
// both, so the distinction is purely how the portal labels the action and who
// owns the artifact's lifetime.
export const supplierDocumentSourceEnum = pgEnum("supplier_document_source", [
  "file",
  "link",
]);

// Account management & security (docs/accounts-security-spec.md). Both enums
// mirror Zod enums in @quagga/types accounts.ts (the validation authority).
export const accountDeletionStatusEnum = pgEnum("account_deletion_status", [
  "pending",
  "cancelled",
  "completed",
]);

export const emailChangeStatusEnum = pgEnum("email_change_status", [
  "pending",
  "confirmed",
  "revoked",
  "expired",
  "cancelled",
]);

export const paymentStatusEnum = pgEnum("payment_status", [
  "pending",
  "reconciled",
  "waived",
]);

// Security events (docs/accounts-security-spec.md §"recent security events").
// The account security page's feed reads a real append-only log of what happened
// to the account, rather than deriving it from `notifications`. Kinds mirror the
// SecurityEventLogKind Zod enum in @quagga/types accounts.ts and the label map in
// @quagga/core (`describeSecurityEvent`). Each value corresponds to an event that
// ALREADY fires in the account actions.
export const securityEventKindEnum = pgEnum("security_event_kind", [
  "password_changed",
  "password_reset_completed",
  "session_revoked",
  "sessions_revoked_others",
  "email_change_requested",
  "email_change_confirmed",
  "email_change_revoked",
  "deletion_requested",
  "deletion_cancelled",
]);

// Notifications & bulletins (docs/notifications-spec.md, build-spec §Notifications).
// One inbox, two origins: personal event notifications + org `bulletin`
// broadcasts. Kinds mirror the NotificationKind Zod enum in @quagga/types and
// the leading-glyph map in @quagga/ui's NotificationItem — keep all three in
// sync.
export const notificationKindEnum = pgEnum("notification_kind", [
  "registration",
  "wrangler",
  "role",
  "questionnaire",
  "supplier",
  "security",
  "bulletin",
]);

// Questionnaire spine (ported 1:1 from Camp 404's pattern).
export const requiredActionTypeEnum = pgEnum("required_action_type", [
  "questionnaire",
  "acknowledgement",
  "payment",
  "profile_update",
]);

export const requiredActionStatusEnum = pgEnum("required_action_status", [
  "pending",
  "completed",
  "waived",
  "expired",
]);

export const questionnaireScopeEnum = pgEnum("questionnaire_scope", [
  "everyone",
  "individual",
  "opt_in",
]);

export const activationStatusEnum = pgEnum("activation_status", [
  "draft",
  "open",
  "closed",
]);

export const questionnaireStatusEnum = pgEnum("questionnaire_status", [
  "draft",
  "published",
  "unpublished",
]);

// Where an activation was authored — the hard boundary results never cross.
// `org` = Organiser Console (org_staff/god); `group` = a project's dashboard.
export const questionnaireAuthoredScopeEnum = pgEnum(
  "questionnaire_authored_scope",
  ["org", "group"],
);

// --- Users ---------------------------------------------------------------
// Camp-specific identity join. Minimal by design: NO role columns — every role
// is a `memberships` row. Account persists; per-edition data hangs elsewhere.

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    authUserId: text("auth_user_id").notNull().unique(),
    email: text("email"),
    // THE handle (migration 0016). Account-level on purpose: the thing it
    // replaced (`burner_bios.display_name`) is PER-EDITION, so a handle there
    // would let one person hold a different name every year and "unique" would
    // mean nothing. Nullable because it is OPTIONAL — a burner can finish
    // onboarding without one and render as the neutral placeholder
    // (@quagga/core `publicMemberName`). Stored AS ENTERED; uniqueness is
    // enforced case-insensitively by the `users_username_lower_idx` unique index
    // on `lower(username)`, and the format rules live in @quagga/core
    // `username.ts` (never duplicated in SQL or in a form).
    username: text("username"),
    // Set when the account has been SANITIZED after a completed deletion request
    // (docs/accounts-security-spec.md §Deletion — the "Lost Cat" precedent). The
    // row survives so memberships, questionnaire responses, and audit events keep
    // referential integrity, but every personal field is erased and the identity
    // renders as the "Departed Burner" stub. A non-null value is also the tombstone
    // that stops a sanitized account being silently re-animated by a later sign-in
    // (@quagga/core `isSanitized` / `assertNotSanitized`).
    sanitizedAt: timestamp("sanitized_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (u) => ({
    // Case-INSENSITIVE uniqueness. A plain unique index on `username` would let
    // `Dusty` and `dusty` coexist, which is exactly the impersonation the handle
    // exists to prevent. Postgres treats NULLs as distinct, so the optional
    // no-username case is unconstrained for free.
    usernameLowerIdx: uniqueIndex("users_username_lower_idx").on(
      sql`lower(${u.username})`,
    ),
  }),
);

// --- Better Auth identity (self-hosted) ----------------------------------
// The Better Auth core tables, owned by @quagga/db and consumed by @quagga/auth's
// drizzleAdapter (provider "pg"). Table + column shapes match Better Auth's
// generated Drizzle schema for 1.6.x EXACTLY (the drizzle adapter looks columns up
// by these camelCase property keys), so this section is effectively adapter-owned:
// do not rename a field or drop a column to fit our house style — that breaks the
// adapter's field mapping. New Better Auth PLUGINS (two-factor, passkey, …) each
// add their own table in a LATER append-only migration when that plugin ships; the
// capability matrix (@quagga/core auth-capabilities) tracks which are live.
//
// WHY THESE SIT BESIDE `users` RATHER THAN BECOMING IT (the near-irreversible call,
// auth-platform-spec §2.3 / decision 2). We deliberately keep TWO tables:
//   - `user`  — the lean auth identity Better Auth owns (credentials, email,
//               verification, OAuth links via `account`, sessions via `session`).
//   - `users` — our app/profile identity, with `sanitized_at` (migration 0011),
//               and the target of EVERY existing FK (memberships, bios,
//               registrations, audit_events, …), joined by `users.auth_user_id`
//               → `user.id`.
// The join stays LOGICAL — there is intentionally NO database foreign key from
// `users.auth_user_id` to `user.id`. That is what protects the "Lost Cat"
// sanitization design (accounts-security-spec §Deletion): the sanitizer
// (`sanitizeAccount`) hard-deletes the Better Auth `user` row (cascading its
// `session`/`account` rows, and erasing the identity's email PII + password hash),
// while our `users` row SURVIVES in its sanitized "Departed Burner" stub form so
// memberships, questionnaire responses and audit history keep referential
// integrity. Its `auth_user_id` is left UNCHANGED by sanitization so the tombstone
// stays findable by the session resolvers, which refuse it via `assertNotSanitized`
// (leaving it pointing at a now-deleted identity id is harmless — the id is random
// and never reissued). A real FK would force us to either cascade-delete that stub
// (destroying the anonymised history POPIA erasure relies on) or block the identity
// deletion entirely — both wrong. Merging the tables would additionally push
// `sanitized_at` and all app
// profile columns onto a Better-Auth-managed table whose shape the adapter dictates
// and whose rows `deleteUser` hard-deletes; the separation is the lower-risk option
// the spec asks for, at the cost of one extra join on identity reads (already how
// the app works today via the external provider — so this cost is unchanged, not
// new).

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  // Added by the Better Auth `twoFactor` plugin (migration 0015). Flipped true
  // once a user has verified a TOTP enrolment; drives the sign-in second-factor
  // challenge. This is a lean flag on the identity — the secret and backup codes
  // live in the separate `two_factor` table (never returned to the client).
  twoFactorEnabled: boolean("two_factor_enabled").notNull().default(false),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { mode: "date" }).notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (s) => ({
    userIdx: index("session_user_id_idx").on(s.userId),
  }),
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", {
      mode: "date",
    }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
      mode: "date",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (a) => ({
    userIdx: index("account_user_id_idx").on(a.userId),
  }),
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { mode: "date" }).notNull(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (v) => ({
    identifierIdx: index("verification_identifier_idx").on(v.identifier),
  }),
);

// DB-backed rate-limit store (auth-platform-spec §6 — the single most dangerous
// silent regression to get wrong). @quagga/auth sets `rateLimit.storage:'database'`
// so limiter counters are SHARED across serverless lambdas; that requires this
// table to exist. Model name `rateLimit` (adapter key), physical table `rate_limit`.
// `last_request` is epoch millis (bigint).
//
// BETTER AUTH OWNS THIS TABLE OUTRIGHT, INCLUDING DELETING FROM IT. Its database
// storage wrapper calls `deleteExpiredRows` after a successful window roll, which
// issues `DELETE … WHERE last_request < now - max(configured window, 10s, 60s)`
// — an UNFILTERED sweep of every row in the table, not only the ones it wrote
// (verified in better-auth 1.6.25, dist/api/rate-limiter/index.mjs). With our
// defaults that cutoff is 60 seconds. Nothing of ours may live here: our own
// counters go in `action_rate_limit` below. The comment this replaces said
// "Better Auth does not auto-TTL them" — it does, and believing otherwise cost
// us a 15-minute password-reset budget (see `action_rate_limit`).
export const rateLimit = pgTable("rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: bigint("last_request", { mode: "number" }).notNull(),
});

// OUR OWN fixed-window counters, for the limits Better Auth never sees
// (migration 0024). `src/rate-limit.ts` is the only writer.
//
// WHY IT IS NOT A NAMESPACE INSIDE `rate_limit`. It was, and that was the bug.
// Better Auth's sweep (above) deletes any row whose `last_request` is older than
// ~60 seconds, and for OUR rows that column holds the WINDOW START, which by
// design does not move for the life of the window. So the forgot-password
// counter — 3 attempts per 15 minutes, shared by all three apps — was deleted
// about a minute into its window by the next piece of auth traffic to touch the
// table, and the next attempt inserted a fresh row with count = 1. A 15-minute
// budget was in practice a 60-second one: 3 reset emails a minute, indefinitely,
// which is enough to flood an inbox and is exactly what the limit exists to
// stop. A separate table is the only fix that does not depend on a library's
// pruning cutoff staying where it is today.
//
// `key` is the primary key (the caller namespaces it, e.g.
// `forgot_password:198.51.100.7`). `window_start` is epoch millis and is the
// window's START, not the last hit — `consumeRateLimit` resets it only when the
// window has elapsed, which is what makes the budget fixed rather than rolling.
// Rows are swept by that same statement once they are long dead; the index is
// what keeps that sweep from scanning the table.
export const actionRateLimit = pgTable(
  "action_rate_limit",
  {
    key: text("key").primaryKey(),
    count: integer("count").notNull(),
    windowStart: bigint("window_start", { mode: "number" }).notNull(),
  },
  (r) => ({
    windowStartIdx: index("action_rate_limit_window_start_idx").on(
      r.windowStart,
    ),
  }),
);

// --- Two-factor authentication (TOTP + backup codes) ---------------------
// Owned by the Better Auth `twoFactor` plugin (better-auth/plugins/two-factor),
// wired in @quagga/auth (migration 0015). One row per user who has STARTED 2FA
// enrolment; `user.twoFactorEnabled` is the "actually on" flag flipped after the
// first TOTP verify. THE SECRET AND BACKUP CODES ARE STORED ENCRYPTED
// (backupCodeOptions.storeBackupCodes:'encrypted' + Better Auth's own secret
// encryption) — never plaintext, which for POPIA-hard-locked accounts would be a
// security failure. Both columns are `returned:false` at the plugin layer, so
// they never leave the server. `failedVerificationCount` + `lockedUntil` back the
// plugin's account-level lockout on the /two-factor/* verify endpoints.
//
// The JS property keys are the Better Auth FIELD names (camelCase) the drizzle
// adapter reads by key; the SQL column names are snake_case, matching how the
// core `user`/`session` tables above are declared.
export const twoFactor = pgTable(
  "two_factor",
  {
    id: text("id").primaryKey(),
    secret: text("secret").notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    verified: boolean("verified").notNull().default(true),
    failedVerificationCount: integer("failed_verification_count")
      .notNull()
      .default(0),
    lockedUntil: timestamp("locked_until", { mode: "date" }),
  },
  (t) => ({
    userIdx: index("two_factor_user_id_idx").on(t.userId),
    secretIdx: index("two_factor_secret_idx").on(t.secret),
  }),
);

// --- Passkeys (WebAuthn) --------------------------------------------------
// Owned by the @better-auth/passkey plugin, wired in @quagga/auth (migration
// 0015). One row per registered credential. `rpID` is scoped to the
// deployment's configured apex domain (AUTH_APEX_DOMAIN, resolved in
// @quagga/auth/env) so a single passkey works across app., org. and
// suppliers. subdomains. Passkeys are ADDITIVE — an accelerator on top
// of password/Google, never the only way in — so losing one is never a lockout
// (recovery: password or 2FA backup code). `counter` is the WebAuthn signature
// counter (clone-detection); `credentialID` is the credential handle.
export const passkey = pgTable(
  "passkey",
  {
    id: text("id").primaryKey(),
    name: text("name"),
    publicKey: text("public_key").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    credentialID: text("credential_id").notNull(),
    counter: integer("counter").notNull(),
    deviceType: text("device_type").notNull(),
    backedUp: boolean("backed_up").notNull(),
    transports: text("transports"),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
    aaguid: text("aaguid"),
  },
  (t) => ({
    userIdx: index("passkey_user_id_idx").on(t.userId),
    credentialIdx: index("passkey_credential_id_idx").on(t.credentialID),
  }),
);

// --- Editions ------------------------------------------------------------
// Years are the root namespace. Bios and registrations hang off an edition.
// Seed: AfrikaBurn 2027 (2027-04-26 → 2027-05-02, active).

export const editions = pgTable("editions", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  year: integer("year").notNull().unique(),
  startDate: date("start_date", { mode: "string" }).notNull(),
  endDate: date("end_date", { mode: "string" }).notNull(),
  isActive: boolean("is_active").notNull().default(false),

  // --- Registration window (migration 0029) --------------------------------
  // When Form 1 opens and closes for this edition. BOTH NULLABLE, and the
  // deadline job treats null as "no deadline set, remind nobody" — a reminder
  // counted against a date nobody entered is a reminder about a deadline that
  // does not exist, and the seeded 2027 edition genuinely has no confirmed
  // opening date yet (roadmap blocker table: "2027 registration opening date",
  // owner AfrikaBurn).
  //
  // Timestamps rather than dates: "closes at 23:59 on the 30th" and "closes at
  // 09:00 on the 30th" are different promises, and the poster will say which.
  //
  // `withTimezone` — the ONE place in this schema where it matters. A bare
  // `timestamp` carries no zone, so the driver returns it interpreted in the
  // Node process's local timezone, and the reminder job does UTC calendar
  // arithmetic against it. On a runner not set to UTC the deadline silently
  // moves. Every other column here records something that happened; these two
  // are a promise compared against `now`.
  registrationOpensAt: timestamp("registration_opens_at", {
    mode: "date",
    withTimezone: true,
  }),
  registrationClosesAt: timestamp("registration_closes_at", {
    mode: "date",
    withTimezone: true,
  }),

  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Burner bios ---------------------------------------------------------
// One row per user × edition (carried forward year to year by confirm-and-copy,
// wave 2+). Field set mirrored from Camp 404's burner profile. `privacy_flags`
// is a per-field public/private map; the HARD-LOCKED always-private fields
// (id_number, passport_number, phone, both emergency contacts, medical) can
// NEVER be set public — enforced in @quagga/core (privacy hard-lock).
//
// ENCRYPTED-AT-REST columns: SA ID / passport AND medical notes are all
// AES-256-GCM encrypted (never stored plaintext); encryption/decryption happens
// at the apps/web write/read boundary via @quagga/db/crypto (`safeEncrypt` /
// `decryptOrNull`). Medical notes are SPECIAL personal information under POPIA
// s26/27 — encrypting them (Ryan, 26 Jul 2026) fixes an earlier sensitivity
// inversion where lower-risk ID data was encrypted while medical was plaintext.
// The `medical_notes` column stays `text` (base64 ciphertext fits), so this
// change needed NO migration — only the write/read code. Like the ID columns,
// medical notes are DROPPED (never persisted) when no PGCRYPTO_KEY is set,
// because SPECIAL data must never fall back to plaintext.
//
// `attended_years` is the set of specific AfrikaBurn years attended (2007–2026,
// never 2020/2021).

export const burnerBios = pgTable(
  "burner_bios",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),

    // Public-toggleable identity fields.
    displayName: text("display_name"),
    legalName: text("legal_name"),
    homeCity: text("home_city"),
    bio: text("bio"),
    skills: jsonb("skills").$type<string[]>().notNull().default([]),
    // Specific AfrikaBurn years attended (2007–2026, never 2020/2021 — no burn).
    attendedYears: jsonb("attended_years")
      .$type<number[]>()
      .notNull()
      .default([]),
    firstTime: boolean("first_time").notNull().default(false),

    // Contact — `email` is display/contact; `phone` is HARD-LOCKED private
    // (stored E.164).
    contactEmail: text("contact_email"),
    phone: text("phone"),

    // HARD-LOCKED private. Two emergency contacts (on-site + off-site), each
    // split into name + phone (E.164). Stored plaintext, like the other
    // contact fields — only id/passport are pgcrypto-encrypted.
    onsiteContactName: text("onsite_contact_name"),
    onsiteContactPhone: text("onsite_contact_phone"),
    offsiteContactName: text("offsite_contact_name"),
    offsiteContactPhone: text("offsite_contact_phone"),
    // HARD-LOCKED private + AES-256-GCM ENCRYPTED at rest (base64 ciphertext in a
    // plain text column — no migration needed to encrypt). Medical is SPECIAL
    // personal information (POPIA s26/27); it is encrypted like the ID columns and
    // dropped rather than stored plaintext when no key is configured.
    medicalNotes: text("medical_notes"),

    // HARD-LOCKED private + pgcrypto-encrypted (base64 ciphertext columns).
    //
    // LAWFUL PURPOSE (Ryan, 26 Jul 2026): SA ID / passport are collected for a
    // single, documented purpose — ON-SITE IDENTITY VERIFICATION against the
    // ticket at the gate (confirming the person arriving is the ticket holder).
    // They are never shared publicly, never shown to other camps, and never used
    // for anything else.
    //
    // BOUNDED RETENTION: because the purpose is spent once the gate closes, this
    // data is PURGEABLE after an edition ends. The purge rule (which editions are
    // expired, plus a small post-event grace) is the pure @quagga/core
    // `id-retention` module (`identifyPurgeableIdBios` / `buildIdPurgePatch`);
    // wiring a scheduled purge job that applies `{ saIdEncrypted: null,
    // passportEncrypted: null }` to expired editions' bios is a LATER task.
    saIdEncrypted: text("sa_id_encrypted"),
    passportEncrypted: text("passport_encrypted"),

    // v3 additions (build-spec §"Burner Bio v3 additions"). All nullable, all
    // self-promotional (never hard-locked). `about` is a "for the burns" bio;
    // `camp_history` is a repeatable list of linked/free-text camps; the ranger
    // trio is inquiry-framed interest, not a commitment.
    about: text("about"),
    campHistory: jsonb("camp_history").$type<CampHistoryEntry[]>(),
    volunteeringInterests: jsonb("volunteering_interests").$type<string[]>(),
    rangerTraining: boolean("ranger_training"),
    rangerCurious: boolean("ranger_curious"),
    greenDotTraining: boolean("green_dot_training"),

    // Per-field public/private map, e.g. { "displayName": true, "bio": true }.
    // Hard-locked fields are force-private regardless of what's stored here.
    privacyFlags: jsonb("privacy_flags")
      .$type<Record<string, boolean>>()
      .notNull()
      .default({}),

    // Questionnaire-engine bookkeeping (this is a "code questionnaire").
    version: text("version").notNull(),
    startedAt: timestamp("started_at", { mode: "date" }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { mode: "date" }),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (b) => ({
    userEditionIdx: uniqueIndex("burner_bios_user_edition_idx").on(
      b.userId,
      b.editionId,
    ),
    editionIdx: index("burner_bios_edition_idx").on(b.editionId),
  }),
);

// --- Profile keys --------------------------------------------------------
// Server-generated keypair at onboarding (reproducible; users never manage
// keys). Used for nothing yet except future QR attestations. The private key is
// stored encrypted; the public key is plaintext.

export const profileKeys = pgTable("profile_keys", {
  userId: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  publicKey: text("public_key").notNull(),
  encryptedPrivateKey: text("encrypted_private_key").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
});

// --- Groups --------------------------------------------------------------
// One joinable-group table. A PROJECT is any non-org group (the kind that
// registers and earns entitlements). Exactly one `org` row is seeded
// ("AfrikaBurn"). `name_normalized` is unique per kind (case/space/punct-
// insensitive; the normalizer lives in @quagga/core).

export const groups = pgTable(
  "groups",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    kind: groupKindEnum("kind").notNull(),
    name: text("name").notNull(),
    nameNormalized: text("name_normalized").notNull(),
    slug: text("slug").notNull(),
    // 60-word limit (for camps) enforced in @quagga/core + the UI.
    description: text("description"),
    joinability: joinabilityEnum("joinability")
      .notNull()
      .default("invite_only"),
    // Reserved column — see groupVisibilityEnum.
    visibility: groupVisibilityEnum("visibility").notNull().default("default"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (g) => ({
    // Unique per kind, case/space/punct-insensitive (normalized upstream).
    kindNameUniq: uniqueIndex("groups_kind_name_normalized_idx").on(
      g.kind,
      g.nameNormalized,
    ),
    slugUniq: uniqueIndex("groups_slug_idx").on(g.slug),
  }),
);

// --- Memberships ---------------------------------------------------------
// user × group with a role. `god` is only valid on the org group (enforced in
// app logic). unique(user, group).

export const memberships = pgTable(
  "memberships",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    role: membershipRoleEnum("role").notNull().default("member"),
    // --- Org departments: NOT HERE ANY MORE (migration 0018) --------------
    // 0017 carried a free-text `department` label + a `department_lead` flag on
    // this row. 0018 DROPS both: departments are now rows in `org_departments`
    // and a person's department comes from the ORG ROLES they hold, each of
    // which may be department-scoped. Two department vocabularies — a label here
    // and a table there — would be exactly the parallel source of truth this
    // change exists to remove, and the label granted nothing anyway.
    // Camp-scoped member reference code, e.g. `MAH-M017` — a stable identifier a
    // camp quotes for its OWN off-platform EFT reconciliation (camper → camp's
    // bank account). NOT an AfrikaBurn payment; the platform never moves money.
    // Nullable: org/god memberships carry none. Unique per group.
    refCode: text("ref_code"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (m) => ({
    userGroupUniq: uniqueIndex("memberships_user_group_idx").on(
      m.userId,
      m.groupId,
    ),
    groupIdx: index("memberships_group_idx").on(m.groupId),
    groupRefCodeUniq: uniqueIndex("memberships_group_ref_code_idx").on(
      m.groupId,
      m.refCode,
    ),
  }),
);

// --- Org departments -----------------------------------------------------
// DATA, NOT CODE (migration 0018). AfrikaBurn's departments — suppliers, theme
// camps, safety, … — are rows a System manager creates, because the org has said
// three times that it cannot yet say how many there are or what protocols they
// carry. Hardcoding a list would be us inventing the org's shape for it; a table
// lets the org tell us, and lets a department-scoped role mean something real.
//
// Creating one SEEDS its LEAD and MEMBER roles (@quagga/core `org-roles`); the
// FK cascade below is why those two live and die with the department.

export const orgDepartments = pgTable(
  "org_departments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    /** Stable slug, derived from the name at creation and never rewritten — it
     * is what the seeded role keys are built from (`suppliers.lead`). */
    key: text("key").notNull(),
    name: text("name").notNull(),
    /** Case/space/punct-insensitive uniqueness key (@quagga/core normalizer). */
    nameNormalized: text("name_normalized").notNull(),
    /** One honest line about what this department answers for. Optional. */
    description: text("description"),
    /**
     * PERMANENCE (migration 0022). `system` departments are seeded and cannot
     * be deleted — Theme camps and Suppliers each back a deployed portal, so a
     * console where they can go missing is a console that can orphan an entire
     * application. Their rights and domains stay editable.
     */
    kind: orgDepartmentKindEnum("kind").notNull().default("custom"),
    sort: integer("sort").notNull().default(0),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (d) => ({
    keyUniq: uniqueIndex("org_departments_key_idx").on(d.key),
    nameUniq: uniqueIndex("org_departments_name_normalized_idx").on(
      d.nameNormalized,
    ),
  }),
);

// --- Org department domains ----------------------------------------------
// WHAT A DEPARTMENT OWNS (migration 0019). Ryan, 27 Jul 2026: "supplier leads
// would be able to read the PII of anything supply-RELATED." That is a subject
// area, not a set of rows — so a department owns DOMAIN KEYS
// (@quagga/core `org-domains`: suppliers, supplier_documents, registrations,
// questionnaires, bulletins, camp_categories, accounts, audit), and an entity's
// department is whichever department owns the domain it lives in.
//
// WHY THIS INSTEAD OF `department_id` ON NINE TABLES: one answer for a whole
// area is one row, not a column every insert path has to remember to fill (and
// the one that forgot would silently produce an unfiled row). It also makes
// re-assignment an upsert rather than a backfill.
//
// `domain` IS THE PRIMARY KEY, so a domain has AT MOST ONE owner — enforced by
// the database, not by a convention. Two departments owning "suppliers" would
// make "whichever department owns its domain" ambiguous, and an ambiguous
// authorisation rule resolves differently depending on row order.
//
// It is TEXT rather than an enum on purpose: the domain vocabulary is a fact
// about the application code, so adding a console area should be a code change,
// not a migration. Unknown keys (a domain a later build removed) are dropped at
// read time and own nothing — fail closed.

export const orgDepartmentDomains = pgTable(
  "org_department_domains",
  {
    /** An `OrgDomain` key from @quagga/core. Unique by construction: one owner. */
    domain: text("domain").primaryKey(),
    departmentId: uuid("department_id")
      .notNull()
      .references(() => orgDepartments.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (d) => ({
    departmentIdx: index("org_department_domains_department_idx").on(
      d.departmentId,
    ),
  }),
);

// --- Org roles -----------------------------------------------------------
// The org's answer to `project_roles`, and deliberately the same shape: key,
// label, KIND (permanence), a `permissions` JSONB object, a curated colour.
//
//   kind = 'system' → seeded, UNDELETABLE, rights EDITABLE.
//   kind = 'custom' → a System manager's own; fully editable and deletable.
//
// `department_id` is what makes "org staff may only delete in their own
// department" expressible without a hardcoded domain→department map: a role
// scoped to a department grants its capabilities ONLY for that department's
// things (`orgCanIn`), while a null department is org-wide.
//
// What is NOT here: `god`. The System manager is anchored on
// `memberships.role = 'god'` and resolves every capability whatever these rows
// say, so no permission edit can define them out of existence.

export const orgRoles = pgTable(
  "org_roles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    /** Stable anchor (`org_staff`, `engineer`, `suppliers.lead`, `custom.<slug>`).
     * Renaming a role changes its label, never this. */
    key: text("key").notNull(),
    departmentId: uuid("department_id").references(() => orgDepartments.id, {
      onDelete: "cascade",
    }),
    name: text("name").notNull(),
    nameNormalized: text("name_normalized").notNull(),
    description: text("description"),
    kind: orgRoleKindEnum("kind").notNull().default("custom"),
    color: roleColorEnum("color").notNull().default("neutral"),
    permissions: jsonb("permissions")
      .$type<OrgPermissions>()
      .notNull()
      .default({}),
    sort: integer("sort").notNull().default(0),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    keyUniq: uniqueIndex("org_roles_key_idx").on(r.key),
    nameUniq: uniqueIndex("org_roles_name_normalized_idx").on(r.nameNormalized),
    departmentIdx: index("org_roles_department_idx").on(r.departmentId),
  }),
);

// --- Org role assignments ------------------------------------------------
// A person holds ZERO OR MORE org roles; `orgCan` resolves the UNION. Composite
// PK makes each assignment unique, exactly like `member_role_assignments`.
// Keyed on the MEMBERSHIP, so removing someone's org access takes their roles
// with it (cascade) rather than leaving orphaned grants to be re-attached by a
// later membership row.

export const orgRoleAssignments = pgTable(
  "org_role_assignments",
  {
    membershipId: uuid("membership_id")
      .notNull()
      .references(() => memberships.id, { onDelete: "cascade" }),
    orgRoleId: uuid("org_role_id")
      .notNull()
      .references(() => orgRoles.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    pk: primaryKey({ columns: [a.membershipId, a.orgRoleId] }),
    roleIdx: index("org_role_assignments_role_idx").on(a.orgRoleId),
  }),
);

// --- Project roles -------------------------------------------------------
// Per-project CUSTOM roles (questionnaire-builder feature) — labels used for
// organisation + questionnaire audiences, distinct from the structural
// `memberships.role` ladder (which governs permissions). Defaults seeded on
// project creation: Captain, Team lead, Burn member. Leads/admins add/rename/
// remove. `name_normalized` is unique per group (case/space/punct-insensitive;
// the normalizer lives in @quagga/core, `normalizeRoleName`).

export const projectRoles = pgTable(
  "project_roles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    nameNormalized: text("name_normalized").notNull(),
    isDefault: boolean("is_default").notNull().default(false),
    sort: integer("sort").notNull().default(0),
    // Roles v2 (questionnaire-spec §"Roles v2"). `kind` = permanence/assignment
    // class; `color`/`emoji` = display; `permissions` = the privilege OBJECT
    // (keys + config, e.g. manage_questionnaires scope). `officerKey` is the
    // stable org catalog anchor for `officer`-kind rows (null otherwise).
    kind: projectRoleKindEnum("kind").notNull().default("custom"),
    color: roleColorEnum("color").notNull().default("neutral"),
    emoji: text("emoji"),
    permissions: jsonb("permissions")
      .$type<ProjectPermissions>()
      .notNull()
      .default({}),
    officerKey: text("officer_key"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (pr) => ({
    groupNameUniq: uniqueIndex("project_roles_group_name_normalized_idx").on(
      pr.groupId,
      pr.nameNormalized,
    ),
    groupIdx: index("project_roles_group_idx").on(pr.groupId),
  }),
);

// --- Member role assignments ---------------------------------------------
// Many-to-many: a membership may hold multiple custom project roles. Composite
// PK (membership_id × project_role_id) makes each assignment unique.

export const memberRoleAssignments = pgTable(
  "member_role_assignments",
  {
    membershipId: uuid("membership_id")
      .notNull()
      .references(() => memberships.id, { onDelete: "cascade" }),
    projectRoleId: uuid("project_role_id")
      .notNull()
      .references(() => projectRoles.id, { onDelete: "cascade" }),
    // Officer consent (questionnaire-spec §"Officers are ALSO registrations").
    // Non-officer assignments are `accepted` immediately; officer assignments
    // start `pending` and the member must accept. `orgVisible` is set true on an
    // officer's acceptance — the SINGLE explicit channel that shares an
    // officer's contact (name/email/phone) with the org (the bio phone
    // hard-lock stays intact everywhere else).
    consentStatus: roleAssignmentConsentEnum("consent_status")
      .notNull()
      .default("accepted"),
    acceptedAt: timestamp("accepted_at", { mode: "date" }),
    orgVisible: boolean("org_visible").notNull().default(false),
    // WHICH EDITION THE CONSENT WAS GIVEN FOR (migration 0023).
    //
    // Consent to share a phone number with AfrikaBurn is consent for ONE burn.
    // Nothing here was edition-scoped: `memberships` is not, this table was
    // not, and nothing resets assignments at rollover — so an officer who
    // accepted in 2026 was still `accepted` + `org_visible` in 2027, and the
    // org console read THIS year's bio (it joins `burner_bios` on the active
    // edition) through LAST year's consent. A phone number, disclosed for a
    // burn the person may not even be attending, on a consent they were never
    // asked for. That is the single POPIA channel in this product, so it is the
    // one place carrying state across editions is not a tidiness question.
    //
    // Nullable, and only officer rows care: an ordinary role chip ("Bar crew")
    // is a camp label with no disclosure attached and legitimately persists.
    // Existing rows are backfilled to the active edition by 0023 — there has
    // only ever been one — so nobody is asked to re-consent for a burn already
    // under way.
    consentEditionId: uuid("consent_edition_id").references(() => editions.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (mra) => ({
    pk: primaryKey({ columns: [mra.membershipId, mra.projectRoleId] }),
    roleIdx: index("member_role_assignments_role_idx").on(mra.projectRoleId),
    consentEditionIdx: index("member_role_assignments_consent_edition_idx").on(
      mra.consentEditionId,
    ),
  }),
);

// --- Invites -------------------------------------------------------------
// One-time links. `kind` = member | lead_transfer.

export const invites = pgTable(
  "invites",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    kind: inviteKindEnum("kind").notNull().default("member"),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    expiresAt: timestamp("expires_at", { mode: "date" }),
    usedByUserId: uuid("used_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    usedAt: timestamp("used_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (i) => ({
    groupIdx: index("invites_group_idx").on(i.groupId),
  }),
);

// --- Registrations -------------------------------------------------------
// group × edition, seven-state workflow. Typed columns for the six sections
// (Finlay's field list, docs/sources/scope-theme-camp-registration.txt). A
// camp is "registered" for an edition IFF an `approved` row exists — the
// `isRegistered` predicate in @quagga/core, from which entitlements derive.
// `completed_sections` records which of the six the wizard has finished; the
// submit-gate (all six complete) lives in @quagga/core.

export const registrations = pgTable(
  "registrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    status: registrationStatusEnum("status").notNull().default("draft"),

    // Section 1 — Identity & contact (camp name/description live on `groups`).
    s1ContactEmail: text("s1_contact_email"),
    s1AltContactName: text("s1_alt_contact_name"),
    s1AltContactPhone: text("s1_alt_contact_phone"),
    s1AltContactEmail: text("s1_alt_contact_email"),

    // Section 2 — Leave No Trace (incl. LNT lead contact).
    s2LntPlan: text("s2_lnt_plan"),
    s2LntLeadName: text("s2_lnt_lead_name"),
    s2LntLeadPhone: text("s2_lnt_lead_phone"),
    s2LntLeadEmail: text("s2_lnt_lead_email"),

    // Section 3 — Participation & gifting.
    s3ParticipationPlan: text("s3_participation_plan"),
    s3OperatingHours: jsonb("s3_operating_hours")
      .$type<string[]>()
      .notNull()
      .default([]),
    s3ScheduleDetail: text("s3_schedule_detail"),
    s3GiftingFood: boolean("s3_gifting_food"),

    // Section 4 — Size & logistics (layout uploads, max 4 — enforced in core).
    s4ExpectedPopulation: integer("s4_expected_population"),
    s4FirstArrivalDate: date("s4_first_arrival_date", { mode: "string" }),
    s4WorkAccessPasses: integer("s4_work_access_passes"),
    s4AreaDimensions: text("s4_area_dimensions"),
    s4LayoutUploadUrls: jsonb("s4_layout_upload_urls")
      .$type<string[]>()
      .notNull()
      .default([]),

    // Section 5 — Sound & placement preferences.
    s5AmplifiedMusic: text("s5_amplified_music"),
    s5SoundPlan: text("s5_sound_plan"),
    s5PlacementFirstChoice: text("s5_placement_first_choice"),
    s5PlacementSecondChoice: text("s5_placement_second_choice"),
    s5NeighbourRequest: text("s5_neighbour_request"),
    s5FamilyFriendly: text("s5_family_friendly"),

    // Section 6 — Suppliers & commerce (structured picker via
    // `supplier_declarations`; this note is free-text overflow).
    s6SuppliersNote: text("s6_suppliers_note"),
    s6PaidPerformers: boolean("s6_paid_performers"),
    s6FeeStructure: text("s6_fee_structure"),
    s6ExpectedBudgetZar: integer("s6_expected_budget_zar"),
    s6PlugAndPlayAck: boolean("s6_plug_and_play_ack"),

    // Grant-interest flag (questionnaire-builder feature). Nullable tri-state:
    // null = not asked yet (no MV/art grant flow), true/false once declared.
    // Drives the `mv_grant_requesters` / `art_grant_requesters` audiences.
    grantsInterest: boolean("grants_interest"),

    // Which of the six sections the wizard has marked complete.
    completedSections: jsonb("completed_sections")
      .$type<string[]>()
      .notNull()
      .default([]),

    submittedAt: timestamp("submitted_at", { mode: "date" }),
    decidedAt: timestamp("decided_at", { mode: "date" }),
    decidedByUserId: uuid("decided_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    // WHY, in the reviewer's own words (migration 0025). Rejecting and asking
    // for changes both REQUIRE a reason, and until this column existed the
    // reason reached only the audit event and the notification — never the
    // camp's own registration page, whose banner points at the per-section
    // feedback thread a reviewer who simply rejected never wrote to.
    decisionReason: text("decision_reason"),

    // --- Staff-assigned placement handles (migration 0029) ----------------
    // Roadmap R1: "Staff-assigned ERFs + camp codes on profiles — unblocks
    // container booking without any placement tool."
    //
    // NEITHER OF THESE IS A PLACEMENT TOOL, and the erf is free text on purpose:
    // AfrikaBurn has not supplied an erf grammar (App Spec §13 is blocked on
    // their mapping process), so a structured column here would be a format we
    // invented and they would then have to match. Normalization lives in
    // @quagga/core `placement-codes`; the moment AB hands over a real format,
    // that module is the only thing that changes.
    //
    // `camp_code` is unique PER EDITION rather than globally: codes are reused
    // year to year for the same camp, and a camp that skips 2028 must not block
    // its own code in 2029.
    campCode: text("camp_code"),
    erf: text("erf"),

    // --- Previous-year duplication (migration 0029) -----------------------
    // The registration this draft was seeded from (roadmap R1's flagship
    // fewer-forms feature). Nullable — a first-time camp carries nothing.
    //
    // `set null` rather than `cascade`: if last year's row is ever removed, this
    // year's registration is still perfectly valid — it just loses the ability
    // to show a diff. Cascading would delete a live registration because of a
    // historical cleanup, which is never the intent.
    carriedForwardFromId: uuid("carried_forward_from_id").references(
      (): AnyPgColumn => registrations.id,
      { onDelete: "set null" },
    ),
    carriedForwardAt: timestamp("carried_forward_at", { mode: "date" }),

    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    groupEditionUniq: uniqueIndex("registrations_group_edition_idx").on(
      r.groupId,
      r.editionId,
    ),
    editionStatusIdx: index("registrations_edition_status_idx").on(
      r.editionId,
      r.status,
    ),
    // Partial unique: two camps in one edition may both be unassigned (NULL),
    // but no two may share a code.
    //
    // BUILT WITHOUT `CONCURRENTLY`, and review asked why. drizzle-kit emits a
    // plain `CREATE UNIQUE INDEX`, and the migrator wraps each migration in a
    // transaction, where `CONCURRENTLY` is not allowed. So the build holds a
    // write lock on `registrations` for as long as it runs. This table holds one
    // row per camp per edition — a few hundred — so that is sub-second. Revisit
    // if the table ever grows by orders of magnitude.
    editionCampCodeUniq: uniqueIndex("registrations_edition_camp_code_idx")
      .on(r.editionId, r.campCode)
      .where(sql`${r.campCode} IS NOT NULL`),
  }),
);

// --- Wrangler assignments -------------------------------------------------
// A wrangler is AfrikaBurn's "dusty guardian angel" for a registered theme camp
// (docs/synthesis.md): an org member from the theme-camp leads team who
// shepherds ONE camp through build week and check-in. Migration 0026.
//
// PER EDITION, because a wrangler relationship is a fact about one burn — not a
// property of the camp. Carrying it across a rollover would re-assign a
// volunteer to a camp they never agreed to shepherd again, which is the mistake
// migration 0023 fixed for officer consent.
//
// ONE PER CAMP PER EDITION (`wranglerGroupEditionUniq`). AfrikaBurn's own words
// are singular, and a camp with two wranglers has none — neither owns the
// follow-up. The other direction is unbounded: a wrangler holds many camps, and
// that read is what the board is.
//
// Reassignment REPLACES this row; the history is in `audit_events`, which is
// already this codebase's answer to who-changed-what. No milestone columns: every
// milestone worth showing today is derivable (registration status, questionnaire
// completion), and storing a copy would mean rendering values nobody sets as
// fact.
export const wranglerAssignments = pgTable(
  "wrangler_assignments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    // `set null`, not cascade: losing the account must not delete the record
    // that this camp HAD a wrangler. The board shows it vacant, which is a
    // thing someone has to act on — not never-assigned, which is not.
    wranglerUserId: uuid("wrangler_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    assignedByUserId: uuid("assigned_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    assignedAt: timestamp("assigned_at", { mode: "date" })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (w) => ({
    wranglerGroupEditionUniq: uniqueIndex(
      "wrangler_assignments_group_edition_idx",
    ).on(w.groupId, w.editionId),
    wranglerEditionIdx: index("wrangler_assignments_wrangler_edition_idx").on(
      w.wranglerUserId,
      w.editionId,
    ),
  }),
);

// --- Section reviews -----------------------------------------------------
// Per-section AB feedback with open/resolved state.

export const sectionReviews = pgTable(
  "section_reviews",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    registrationId: uuid("registration_id")
      .notNull()
      .references(() => registrations.id, { onDelete: "cascade" }),
    sectionKey: sectionKeyEnum("section_key").notNull(),
    status: sectionReviewStatusEnum("status").notNull().default("open"),
    comment: text("comment").notNull(),
    reviewerId: uuid("reviewer_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sr) => ({
    registrationIdx: index("section_reviews_registration_idx").on(
      sr.registrationId,
    ),
  }),
);

// --- Section review replies ----------------------------------------------
// Camp-side (and org-side) replies THREADED under a `section_reviews` row. The
// design frames show a per-section reply box beneath a flagged review so a camp
// can answer the placement team; `section_reviews` is org-authored only, so this
// carries the responses. Authz (server-side, @quagga/core `canReplyToSectionReview`):
// only a MEMBER of the camp under review may reply, and org staff may reply too.
// `author_user_id` is nullable + `set null` on user delete, matching the other
// authored-content tables (`section_reviews.reviewer_id`, `supplier_notes.author_id`)
// — our `users` rows survive account sanitization as stubs, so authorship persists
// in practice. The reply UI is built by a LATER agent (this is schema + action only).
export const sectionReviewReplies = pgTable(
  "section_review_replies",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    reviewId: uuid("review_id")
      .notNull()
      .references(() => sectionReviews.id, { onDelete: "cascade" }),
    authorUserId: uuid("author_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (srr) => ({
    reviewIdx: index("section_review_replies_review_idx").on(srr.reviewId),
  }),
);

// --- Questionnaire spine (ported 1:1 from Camp 404) ----------------------
// The Burner Bio dispatches through this; `required_actions` is the generic
// "what blocks this user" gate that routes onboarding.

export const questionnaireDefinitions = pgTable("questionnaire_definitions", {
  key: text("key").primaryKey(),
  title: text("title").notNull(),
  definition: jsonb("definition").$type<Questionnaire>().notNull(),
  status: questionnaireStatusEnum("status").notNull().default("draft"),
  version: text("version"),
  createdByUserId: uuid("created_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
});

export const questionnaireActivations = pgTable(
  "questionnaire_activations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    questionnaireKey: text("questionnaire_key").notNull(),
    version: text("version").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    scope: questionnaireScopeEnum("scope").notNull().default("everyone"),
    blocking: boolean("blocking").notNull().default(true),
    status: activationStatusEnum("status").notNull().default("draft"),
    dueAt: timestamp("due_at", { mode: "date" }),
    // Audience-targeting columns (questionnaire-builder feature). `authoredScope`
    // + `groupId` are the results-visibility boundary; `audience` is the jsonb
    // spec resolved at send time (@quagga/core resolveAudience); `editionId`
    // scopes edition-relative selectors. All nullable so pre-feature rows (the
    // Burner Bio spine) are untouched.
    authoredScope: questionnaireAuthoredScopeEnum("authored_scope")
      .notNull()
      .default("org"),
    groupId: uuid("group_id").references(() => groups.id, {
      onDelete: "cascade",
    }),
    editionId: uuid("edition_id").references(() => editions.id, {
      onDelete: "cascade",
    }),
    audience: jsonb("audience").$type<AudienceSpec>(),
    // The definition AS SENT, snapshotted at activation time. An activation must
    // render/validate/aggregate against exactly what its respondents were shown —
    // editing (or re-versioning) the live `questionnaire_definitions` row must
    // never mutate an in-flight or already-answered activation. Nullable so
    // pre-snapshot rows (activated before this column existed) fall back to the
    // live join at read time; no backfill required. Re-activation snapshots the
    // new version, which is correct.
    definition: jsonb("definition").$type<Questionnaire>(),
    activatedByUserId: uuid("activated_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    openedAt: timestamp("opened_at", { mode: "date" }),
    closedAt: timestamp("closed_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    keyIdx: index("questionnaire_activations_key_idx").on(a.questionnaireKey),
    statusIdx: index("questionnaire_activations_status_idx").on(a.status),
    groupIdx: index("questionnaire_activations_group_idx").on(a.groupId),
    editionIdx: index("questionnaire_activations_edition_idx").on(a.editionId),
  }),
);

export const questionnaireResponses = pgTable(
  "questionnaire_responses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    definitionKey: text("definition_key").notNull(),
    /**
     * THE YEAR NAMESPACE (migration 0020).
     *
     * Answers belong to an AfrikaBurn edition. Re-sending a questionnaire
     * WITHIN one edition keeps updating the same row, which is the intended
     * behaviour — the person is revising a living answer and the runner shows
     * them what they said last time. A NEW edition is a clean namespace.
     *
     * Without this column the identity was (user, definition_key) forever, and
     * org questionnaire keys are stable across years (`org-<title-slug>`), so
     * answering "Volunteer availability" in 2028 silently overwrote the same
     * person's 2027 answer and there was no way to compare the two.
     */
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    definitionVersion: text("definition_version").notNull(),
    responses: jsonb("responses")
      .$type<QuestionnaireResponses>()
      .notNull()
      .default({}),
    activationId: uuid("activation_id").references(
      () => questionnaireActivations.id,
      { onDelete: "set null" },
    ),
    /**
     * WHICH CAMP this answer is about, when the questionnaire asks about a camp
     * rather than a person (migration 0028, Form 2 — roadmap M4-20).
     *
     * Null for every questionnaire that really is about the respondent: the
     * Burner Bio spine, the org's internal check-ins. Set for Form 2, which asks
     * how big your camp is, where it wants to be and what noise it will make —
     * none of which are facts about the person filling it in.
     *
     * It exists because a person may lead more than one approved camp. Without
     * it that lead has ONE Form-2 answer for TWO camps, and mirroring it onto a
     * registration means guessing which camp they meant.
     */
    groupId: uuid("group_id").references(() => groups.id, {
      onDelete: "cascade",
    }),
    completedAt: timestamp("completed_at", { mode: "date" }),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    // Identity is (user, questionnaire, EDITION) for a PERSON-scoped answer, and
    // (user, questionnaire, EDITION, CAMP) for a camp-scoped one. Re-sending
    // inside one edition updates the row; a new edition gets its own.
    //
    // TWO PARTIAL INDEXES rather than one widened index, because Postgres treats
    // NULLs as DISTINCT in a unique index: adding `group_id` to the existing one
    // would have quietly allowed unlimited duplicate Burner Bio rows per person.
    // Splitting them states the rule instead of relying on a NULL subtlety.
    userDefIdx: uniqueIndex("questionnaire_responses_user_def_idx")
      .on(r.userId, r.definitionKey, r.editionId)
      .where(sql`${r.groupId} is null`),
    userDefGroupIdx: uniqueIndex("questionnaire_responses_user_def_group_idx")
      .on(r.userId, r.definitionKey, r.editionId, r.groupId)
      .where(sql`${r.groupId} is not null`),
    defIdx: index("questionnaire_responses_def_idx").on(r.definitionKey),
    // "Which approved camps have returned this form?" — the org's chase list.
    groupIdx: index("questionnaire_responses_group_idx").on(
      r.groupId,
      r.definitionKey,
    ),
  }),
);

// A required action belongs to AN EDITION (migration 0024). It is keyed
// (user, EDITION, action_key), not (user, action_key).
//
// The Burner Bio is why. `burner_bios` has always been per-edition — a bio is
// re-confirmed for each burn, because contact numbers, emergency contacts and
// medical notes go stale in a year and the whole point of collecting them is
// that they are true when someone is in the desert. The GATE that makes a
// burner do that re-confirmation is a `required_actions` row with
// `action_key = 'burner_bio'`, and while the key was (user, action_key) there
// could only ever be ONE such row per person, FOREVER: completed for 2027,
// still completed in 2028, `ensureRequiredAction`'s ON CONFLICT DO NOTHING
// silently discarding the new edition's row. The gate fired once in a burner's
// lifetime and then never again, and nothing anywhere reported that — the 2028
// onboarding simply never appeared and every 2027 phone number was treated as
// current.
//
// Ryan, 28 Jul 2026: the bio PERSISTS across editions but must be UPDATED once
// per edition, so the gate must fire again. The edition in the key is what
// makes "again" expressible.
export const requiredActions = pgTable(
  "required_actions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** The edition this action is owed FOR. Part of the uniqueness key. */
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    type: requiredActionTypeEnum("type").notNull(),
    actionKey: text("action_key").notNull(),
    version: text("version"),
    activationId: uuid("activation_id").references(
      () => questionnaireActivations.id,
      { onDelete: "set null" },
    ),
    title: text("title").notNull(),
    blocking: boolean("blocking").notNull().default(true),
    status: requiredActionStatusEnum("status").notNull().default("pending"),
    dueAt: timestamp("due_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { mode: "date" }),
  },
  (ra) => ({
    // The edition sits in the MIDDLE so the index still serves a lookup by user
    // alone (`listRequiredActions`) on its leading column.
    userEditionActionIdx: uniqueIndex(
      "required_actions_user_edition_action_idx",
    ).on(ra.userId, ra.editionId, ra.actionKey),
    userStatusIdx: index("required_actions_user_status_idx").on(
      ra.userId,
      ra.status,
    ),
  }),
);

// --- Suppliers -----------------------------------------------------------
// Supplier model v2 (docs/supplier-spec.md). `source`/`vetting_status` are
// gone; the org sees three things only — did they onboard (derived from
// `supplier_onboarding`), what `standing` are they in, and the notes trail
// (`supplier_notes`). `userId` optionally links a supplier to a burner account
// (matched by email overlap) so a supplier can sign into their own portal.

export const suppliers = pgTable(
  "suppliers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: text("name").notNull(),
    // Human-quotable supplier reference, e.g. `SUP-2027-0416` (the canvas chip).
    // STORED, not derived — deliberately: the code is quoted OFF-platform (depot
    // gate lists, delivery manifests, the supplier's own paperwork), so once
    // issued it must never change. A derived code would silently re-key itself
    // the moment its inputs moved (a renamed business, a re-sorted list, a
    // re-imported sheet), and suppliers carry no stable per-edition ordinal to
    // derive a sequence from in the first place. Format + issuance helpers live
    // in @quagga/core (`formatSupplierCode`, `nextSupplierSequence`). Nullable:
    // imported rows predate the scheme and are backfilled lazily on first need.
    code: text("code").unique(),
    services: text("services"),
    contact: text("contact"),
    website: text("website"),
    // Normalised category chip ported from the sheet's Category column
    // (Transportation→Transport, FIREWOOD DELIVERY→Firewood Delivery, title-
    // cased; multiple joined with " / "). Nullable — hand-added suppliers may
    // carry none.
    category: text("category"),
    // Returning vs newbie, ported from the sheet's "Returning Supplier?"
    // column. Nullable — blank sheet cells / hand-added rows carry none.
    returning: supplierReturningEnum("returning"),
    // Org-set verdict, visible everywhere (org console + camp-side picker).
    standing: supplierStandingEnum("standing").notNull().default("good"),
    // Optional account link (email overlap). Nullable — most imported rows have
    // no signed-in supplier yet.
    userId: uuid("user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    importedAt: timestamp("imported_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (s) => ({
    nameIdx: index("suppliers_name_idx").on(s.name),
    standingIdx: index("suppliers_standing_idx").on(s.standing),
    userIdx: index("suppliers_user_idx").on(s.userId),
  }),
);

// --- Supplier onboarding -------------------------------------------------
// Per supplier × edition onboarding checklist state. The seven steps + their
// completion/confirmation semantics are a code catalog
// (@quagga/core SUPPLIER_ONBOARDING_STEPS); `steps` is the jsonb state map
// (stepKey → status). Progress (n/7) and "onboarded properly" derive in core.

export const supplierOnboarding = pgTable(
  "supplier_onboarding",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    steps: jsonb("steps")
      .$type<SupplierOnboardingSteps>()
      .notNull()
      .default({}),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (so) => ({
    supplierEditionUniq: uniqueIndex(
      "supplier_onboarding_supplier_edition_idx",
    ).on(so.supplierId, so.editionId),
    editionIdx: index("supplier_onboarding_edition_idx").on(so.editionId),
  }),
);

// --- Supplier notes ------------------------------------------------------
// Org-internal timeline about a supplier (infraction / blessing / note). Never
// visible to the supplier or to camps. POPIA-relevant — audit-logged upstream.

export const supplierNotes = pgTable(
  "supplier_notes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    authorId: uuid("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    kind: supplierNoteKindEnum("kind").notNull().default("note"),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sn) => ({
    supplierIdx: index("supplier_notes_supplier_idx").on(sn.supplierId),
  }),
);

// --- Supplier documents --------------------------------------------------
// Org-controlled, per-edition list of documents/links suppliers must read
// (docs/accounts-security-spec.md §"Supplier documents — org-controlled"). The
// org console CRUDs these; the supplier portal renders them as the Documents
// panel on the onboarding page. `required_ack` rows carry an acknowledgement
// checkbox; `step_key` optionally BINDS the document to an onboarding step, so
// acknowledging every required document bound to that step completes it
// (@quagga/core `applyDocumentAcksToSteps`). Binding to an ORG-CONFIRMED step
// (deposit / briefing / fee) is rejected in core — a supplier ticking a box must
// never confirm money or attendance.

export const supplierDocuments = pgTable(
  "supplier_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    sourceType: supplierDocumentSourceEnum("source_type")
      .notNull()
      .default("link"),
    // The external URL or the uploaded asset's blob URL.
    url: text("url").notNull(),
    requiredAck: boolean("required_ack").notNull().default(false),
    // Optional binding to a SupplierOnboardingStepKey. Plain text (not an enum
    // column) to match how `supplier_onboarding.steps` stores keys; validated by
    // the Zod enum at the boundary.
    stepKey: text("step_key"),
    sort: integer("sort").notNull().default(0),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sd) => ({
    editionSortIdx: index("supplier_documents_edition_sort_idx").on(
      sd.editionId,
      sd.sort,
    ),
    editionStepIdx: index("supplier_documents_edition_step_idx").on(
      sd.editionId,
      sd.stepKey,
    ),
  }),
);

// --- Supplier document acknowledgements ----------------------------------
// supplier × document, composite PK (one ack per pair, idempotent). `acked_at`
// is the evidence timestamp. Un-acknowledging deletes the row.

export const supplierDocumentAcks = pgTable(
  "supplier_document_acks",
  {
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    documentId: uuid("document_id")
      .notNull()
      .references(() => supplierDocuments.id, { onDelete: "cascade" }),
    ackedAt: timestamp("acked_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    pk: primaryKey({ columns: [a.supplierId, a.documentId] }),
    documentIdx: index("supplier_document_acks_document_idx").on(a.documentId),
  }),
);

// --- Supplier declarations -----------------------------------------------
// registration × supplier — the structured Section 6 picker (replaces the
// free-text suppliers field).

export const supplierDeclarations = pgTable(
  "supplier_declarations",
  {
    registrationId: uuid("registration_id")
      .notNull()
      .references(() => registrations.id, { onDelete: "cascade" }),
    supplierId: uuid("supplier_id")
      .notNull()
      .references(() => suppliers.id, { onDelete: "cascade" }),
    note: text("note"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (sd) => ({
    pk: primaryKey({ columns: [sd.registrationId, sd.supplierId] }),
    supplierIdx: index("supplier_declarations_supplier_idx").on(sd.supplierId),
  }),
);

// --- Payments ------------------------------------------------------------
// Payment DETAILS + reference + status only. No processing, ever. Polymorphic
// subject by string key (`subject_type` + `subject_id`). `reference` is
// human-readable, e.g. QP-2027-MAH-001 (generator in @quagga/core).

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    subjectType: text("subject_type").notNull(),
    subjectId: uuid("subject_id").notNull(),
    amountCents: integer("amount_cents"),
    currency: text("currency").notNull().default("ZAR"),
    reference: text("reference").notNull().unique(),
    status: paymentStatusEnum("status").notNull().default("pending"),
    details: jsonb("details").$type<Record<string, unknown>>(),
    recordedByUserId: uuid("recorded_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (p) => ({
    subjectIdx: index("payments_subject_idx").on(p.subjectType, p.subjectId),
    statusIdx: index("payments_status_idx").on(p.status),
  }),
);

// --- Audit events --------------------------------------------------------
// Written on: elevation, approval/rejection, payment reconciliation.

export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    actorId: uuid("actor_id").references(() => users.id, {
      onDelete: "set null",
    }),
    action: text("action").notNull(),
    subject: text("subject"),
    meta: jsonb("meta").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (a) => ({
    actorIdx: index("audit_events_actor_idx").on(a.actorId),
    actionIdx: index("audit_events_action_idx").on(a.action),
    // Added in migration 0024. `audit_events` is APPEND-ONLY and never pruned,
    // so it is the one table here that only ever grows — and until these two
    // existed, three hot readers scanned all of it:
    //   · the status board's recent-activity card and the audit trail page,
    //     both `ORDER BY created_at DESC LIMIT n` over the whole log;
    //   · the medical access log, `created_at >= <lookback>` (the action index
    //     narrowed that one, the date range did not);
    //   · POPIA erasure, which rewrites `meta` `WHERE actor_id = … OR subject = …`
    //     and had an index for the first half of that OR and none for the second.
    // DESC to match how every reader orders it (Postgres can walk a btree
    // backwards, but the matching order lets `ORDER BY … LIMIT` stop at n).
    subjectIdx: index("audit_events_subject_idx").on(a.subject),
    createdAtIdx: index("audit_events_created_at_idx").on(a.createdAt.desc()),
    // Migration 0029. PARTIAL, and scoped to the one action on purpose: this
    // table is append-only and (action, subject) is deliberately NOT unique in
    // general — a camp can be approved, reopened and approved again, and every
    // row must survive. The deadline-reminder job is the exception: it CLAIMS
    // this marker with a conflict-safe insert so its idempotency is enforced by
    // the database rather than by a check-then-write that two concurrent cron
    // deliveries both pass.
    //
    // BUILT WITHOUT `CONCURRENTLY`, for the same reason as the camp-code index:
    // the migrator runs each migration in a transaction, where `CONCURRENTLY`
    // is not allowed. Partial or not, the build scans the whole table once and
    // blocks audit writes while it does. At today's volume — one row per console
    // action — that is well under a second. This table only grows, so revisit
    // before adding another index to it once it is large.
    deadlineReminderMarker: uniqueIndex(
      "audit_events_deadline_reminder_marker_idx",
    )
      .on(a.action, a.subject)
      .where(sql`${a.action} = 'registration.deadline_reminder'`),
  }),
);

// --- Bulletins -----------------------------------------------------------
// Org-authored broadcast to an AUDIENCE (reuses the questionnaire audience
// machinery verbatim — `audience` is the same jsonb AudienceSpec as
// `questionnaire_activations.audience`; resolution is @quagga/core
// `resolveAudience`, one resolver, two consumers). A bulletin is a draft until
// `published_at` is stamped; publishing fans out one `notifications` row (kind
// `bulletin`) per resolved recipient. Also a standalone deep-linkable page.
// Informational only — bulletins never collect data (fewer-forms law).

export const bulletins = pgTable(
  "bulletins",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    bodyMd: text("body_md").notNull(),
    // Same enum/shape as questionnaire audiences (validated by AudienceSpec in
    // @quagga/types; resolved by @quagga/core resolveAudience at publish time).
    audience: jsonb("audience").$type<AudienceSpec>().notNull(),
    createdByUserId: uuid("created_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    // Null = draft; set on publish (the fan-out trigger).
    publishedAt: timestamp("published_at", { mode: "date" }),
    pinned: boolean("pinned").notNull().default(false),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (b) => ({
    editionIdx: index("bulletins_edition_idx").on(b.editionId),
    publishedIdx: index("bulletins_published_idx").on(b.publishedAt),
  }),
);

// --- Camp categories -----------------------------------------------------
// Org-defined per-edition "theme topics" taxonomy (build-spec §"Camp
// categories"). The org CRUDs the catalog per edition (label, optional emoji,
// sort); camps pick ≥0 via `group_categories`. `label_normalized` (the
// @quagga/core `normalizeCategoryLabel`) is unique per edition — dedupe is
// case/space/punct-insensitive, mirroring the groups name-dedupe pattern.

export const campCategories = pgTable(
  "camp_categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    editionId: uuid("edition_id")
      .notNull()
      .references(() => editions.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    labelNormalized: text("label_normalized").notNull(),
    // Optional display emoji (curated by the org — free text, single glyph).
    emoji: text("emoji"),
    sort: integer("sort").notNull().default(0),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (c) => ({
    editionLabelUniq: uniqueIndex("camp_categories_edition_label_idx").on(
      c.editionId,
      c.labelNormalized,
    ),
    editionSortIdx: index("camp_categories_edition_sort_idx").on(
      c.editionId,
      c.sort,
    ),
  }),
);

// --- Group ↔ category join -----------------------------------------------
// Many-to-many: a group (camp/project) picks zero or more categories from its
// edition's catalog. Composite PK makes each pick unique; the reverse index
// powers per-category usage counts + the directory filter. The category's
// edition scope is enforced in @quagga/core / the store (a group may only pick
// from its active edition's catalog).

export const groupCategories = pgTable(
  "group_categories",
  {
    groupId: uuid("group_id")
      .notNull()
      .references(() => groups.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id")
      .notNull()
      .references(() => campCategories.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (gc) => ({
    pk: primaryKey({ columns: [gc.groupId, gc.categoryId] }),
    categoryIdx: index("group_categories_category_idx").on(gc.categoryId),
  }),
);

// --- Notifications -------------------------------------------------------
// Per-account inbox. Append-only; `read_at` set on open ("mark all read" bulk-
// sets it). Generated by EXISTING events (registration decisions, wrangler
// assignment, role/officer acceptance, questionnaire release, supplier org-
// confirmations, security events) + bulletin fan-out. `bulletin_id` links a
// `bulletin`-kind row back to its source. NO new PII — previews never carry
// hard-locked fields (enforced by the @quagga/core payload builders).

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: notificationKindEnum("kind").notNull(),
    title: text("title").notNull(),
    body: text("body"),
    link: text("link"),
    /**
     * WHO SENT IT (migration 0021) — `org`, `camp`, or `system`.
     *
     * Provenance, and only provenance: "AfrikaBurn asked you this" and "your
     * camp lead asked you this" are different things to the person reading the
     * inbox, and nothing on the row said which.
     */
    origin: text("origin"),
    /**
     * WHICH APP THE LINK RESOLVES IN (migration 0021) — `web`, `org` or
     * `suppliers`.
     *
     * Deliberately SEPARATE from `origin`, because they genuinely differ: the
     * org console writes the supplier inbox, so those rows are sent BY org and
     * read IN the suppliers app. Conflating the two is what produced the proven
     * 404 — one table, three apps, and a bare app-relative `link` that means a
     * different route depending on who reads it.
     *
     * Nullable on purpose. All three apps run migrations at build time, so
     * whichever deploys first would otherwise be writing a column the other two
     * do not yet bind — and every notification insert swallows its own
     * exception, so that failure would be silent. Null means "unknown, treat as
     * local", which is exactly the pre-migration behaviour.
     */
    linkApp: text("link_app"),
    bulletinId: uuid("bulletin_id").references(() => bulletins.id, {
      onDelete: "cascade",
    }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    readAt: timestamp("read_at", { mode: "date" }),
  },
  (n) => ({
    // Unread count + filter: (user, read_at).
    userReadIdx: index("notifications_user_read_idx").on(n.userId, n.readAt),
    // Inbox list, newest first: (user, created_at desc).
    userCreatedIdx: index("notifications_user_created_idx").on(
      n.userId,
      n.createdAt.desc(),
    ),
  }),
);

// --- Account deletion requests -------------------------------------------
// docs/accounts-security-spec.md §Deletion. Deleting an account is NEVER a row
// delete. Re-auth to request → a 14-day grace period (cancelled by simply
// signing in) → then SANITIZATION (the Camp 404 "Lost Cat" precedent): personal
// fields are erased and the identity is anonymized to a "Departed Burner" stub
// so memberships, questionnaire responses, and audit events keep referential
// integrity and POPIA erasure is still satisfied.
//
// `grace_ends_at` is STORED rather than derived from `requested_at + 14d` on
// read: a later policy change to the grace length must never retroactively
// shorten a window someone was already promised.
//
// One LIVE request per user is enforced by a partial unique index (`WHERE
// status = 'pending'`), not a plain unique on `user_id`: a burner who cancels
// and later changes their mind must be able to request again.

export const accountDeletionRequests = pgTable(
  "account_deletion_requests",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    status: accountDeletionStatusEnum("status").notNull().default("pending"),
    requestedAt: timestamp("requested_at", { mode: "date" })
      .notNull()
      .defaultNow(),
    /** When the grace period elapses and sanitization becomes due. */
    graceEndsAt: timestamp("grace_ends_at", { mode: "date" }).notNull(),
    cancelledAt: timestamp("cancelled_at", { mode: "date" }),
    /** Set when sanitization has actually been applied. */
    completedAt: timestamp("completed_at", { mode: "date" }),
    /** Which app the request came from (`web` | `org` | `suppliers`) — trail only. */
    requestedFromApp: text("requested_from_app"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    userStatusIdx: index("account_deletion_requests_user_status_idx").on(
      r.userId,
      r.status,
    ),
    // The sweeper's query: pending requests whose grace has elapsed.
    dueIdx: index("account_deletion_requests_due_idx").on(
      r.status,
      r.graceEndsAt,
    ),
    // At most one PENDING request per user; cancelled/completed rows stay as
    // history and never block a fresh request.
    onePendingPerUser: uniqueIndex("account_deletion_requests_one_pending_idx")
      .on(r.userId)
      .where(sql`${r.status} = 'pending'`),
  }),
);

// --- Email change requests -----------------------------------------------
// docs/accounts-security-spec.md §"Email change": confirm via the NEW address,
// notify the OLD address with a revocation link, revocable for 48h.
//
// WHY WE OWN THIS TABLE. Managed Neon Auth's SERVER SDK exposes no
// `change-email` endpoint (its typed endpoint allowlist covers change-password,
// request/reset-password, verify-email, list/revoke-sessions, delete-user — but
// not change-email), and we cannot add a Better Auth server plugin on a managed
// instance. Even if the browser client's `changeEmail` reaches the upstream
// instance through the `/api/auth/*` proxy, Better Auth's own flow has no 48h
// revocation window — that requirement is OURS regardless of the provider. So
// this table is the record of the request, the confirmation, and the revocation
// window; committing the new address at the identity provider is a separate,
// explicitly-gated step that FAILS SAFE when the provider cannot do it (see
// `@quagga/core` AUTH_CAPABILITIES and the app-side commit seam). A row here is
// never treated as proof the address changed — only `status = 'confirmed'` plus
// a successful provider commit is.
//
// Tokens are stored as SHA-256 HASHES, never plaintext: a database leak must
// not hand an attacker a live confirmation or revocation link.

export const emailChangeRequests = pgTable(
  "email_change_requests",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /** The address at request time — the one that gets the revocation notice. */
    currentEmail: text("current_email").notNull(),
    newEmail: text("new_email").notNull(),
    status: emailChangeStatusEnum("status").notNull().default("pending"),
    /** SHA-256 of the single-use confirmation token emailed to the NEW address. */
    confirmTokenHash: text("confirm_token_hash").notNull().unique(),
    /** SHA-256 of the revocation token emailed to the OLD address. */
    revokeTokenHash: text("revoke_token_hash").notNull().unique(),
    /** Confirmation-token expiry (short-lived, enumeration-safe). */
    expiresAt: timestamp("expires_at", { mode: "date" }).notNull(),
    confirmedAt: timestamp("confirmed_at", { mode: "date" }),
    /** confirmedAt + 48h; stored so a policy change can't shrink a live window. */
    revocableUntil: timestamp("revocable_until", { mode: "date" }),
    revokedAt: timestamp("revoked_at", { mode: "date" }),
    /**
     * Set only when the address was actually changed AT THE IDENTITY PROVIDER.
     * Null on a `confirmed` row means the provider commit has not happened (or
     * is not currently possible) — the app must never present that as success.
     */
    providerCommittedAt: timestamp("provider_committed_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { mode: "date" }).notNull().defaultNow(),
  },
  (r) => ({
    userStatusIdx: index("email_change_requests_user_status_idx").on(
      r.userId,
      r.status,
    ),
    // At most one PENDING (unconfirmed) request per user — a second request
    // supersedes the first, which the action cancels before inserting. Confirmed
    // rows are excluded so the 48h revocation history survives.
    onePendingPerUser: uniqueIndex("email_change_requests_one_pending_idx")
      .on(r.userId)
      .where(sql`${r.status} = 'pending'`),
  }),
);

// --- Security events ------------------------------------------------------
// docs/accounts-security-spec.md §"recent security events". An append-only log of
// what actually happened to an account, recorded at the moment each account action
// succeeds. This REPLACES the earlier stopgap where the security page derived its
// feed from `notifications` (which conflated inbox messages with the event record).
//
// Recording is THIN and BEST-EFFORT — a failed insert here must never roll back
// (or fail) the primary security action it describes. `ip`/`user_agent` are the
// request context at the time of the event (both nullable — not every event has a
// request, e.g. the sign-in-driven deletion cancel). `kind` is the typed event
// class (mirrors SecurityEventLogKind in @quagga/types; display strings come from
// @quagga/core `describeSecurityEvent` so no PII/labels are stored here).
export const securityEvents = pgTable(
  "security_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: securityEventKindEnum("kind").notNull(),
    ip: text("ip"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at", { mode: "date" }).notNull().defaultNow(),
  },
  (e) => ({
    // The feed query: an account's events, newest first.
    userCreatedIdx: index("security_events_user_created_idx").on(
      e.userId,
      e.createdAt.desc(),
    ),
  }),
);
